### ISSUE TITLE
what > when?

### ISSUE THREAD

**Issue by krisgesling** [retrodaredevil/pokemon-skill#4]
Hey Joshua, 

One of our translators was confused by [evolve.details.knowing.move.type.dialog](https://github.com/retrodaredevil/pokemon-skill/blob/8d8c809cf34de93a36d93d21826446daacf6309d/dialog/en-us/evolve.details.knowing.move.type.dialog) and I'm wondering if it should be:
> when knowing a move with type {type}

rather than:
> what knowing a move with type {type}

**Comment by retrodaredevil** [comment]
Yes, that looks like a typo on my part. It should be "when knowing a move with type {type}"

I'll try to fix it in the next few days. 

Thanks for pointing that out to me

**Comment by retrodaredevil** [comment]
I fixed this bug a while ago but left this open so I would remember to make a pull request on the skills repository. I finally did that.

https://github.com/retrodaredevil/pokemon-skill/commit/160a8d0d8e0742ff9198e7fd00683045af895da0

https://github.com/MycroftAI/mycroft-skills/pull/1144
