### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by krisgesling** [retrodaredevil/pokemon-skill#5]
Hey there, just a heads up, I noticed the url used for the icon seems to have broken at some point.

**Comment by retrodaredevil** [comment]
Thank you for letting me know. It is fixed now.

https://github.com/retrodaredevil/pokemon-skill/commit/cc0aeb889ef7aea1b344909e7eb8904883f62bff

https://github.com/MycroftAI/mycroft-skills/pull/1144
