### ISSUE TITLE
Make tagged releases

### ISSUE THREAD

**Issue by PureTryOut** [retrodaredevil/pokemon-skill#7]
Hey, thanks for this skill!

I've been packaging Mycroft for Alpine Linux (which I think is the first distribution to do so) and am currently packaging all the different skills available. The idea is to make all skills available as distro packages and not use the current Mycroft marketplace and Pip to install them. I'd love to package your skill as well, but will need a tagged (`git tag`) release to do so.

Please consider making tagged release so that distributions like Alpine Linux and in the future others can package them and keep track of updates.

**Comment by retrodaredevil** [comment]
That sounds pretty cool. I created a tag: "v1.1.1". I'll try to keep this up to date with the mycroft skills repository the next time I update this.

**Comment by PureTryOut** [comment]
Awesome, thanks! I made a merge request to get it into Alpine's testing repositories, you can track it's progress [here](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7729).
